### ISSUE TITLE
BE_DATA_VALUE可能引起的.h头文件重定义问题

### ISSUE THREAD

**Issue by afas2005** [DawsenSu/PDWIT_Waterway#2]
建议修改
#define BE_DATA_VALUE(type, var) \
public: \
        type Get##var() const \
        { \
                return m_##var; \
        } \
        type &Pop##var() \
        { \
                return m_##var; \
        } \
        void Set##var(type arg) \
        { \
                m_##var = arg; \
        } \
private: \
        type m_##var;
为如下两个宏，
#define DECLARE_PROPERTY(type, var) \
public: \
        type Get##var() const; \
        type &Pop##var(); \
        void Set##var(type arg); \
private: \
        type m_##var; \
	
#define DEFINE_PROPERTY(ClassName, type, var) \
        type ClassName##::Get##var() const \
        { \
                return m_##var; \
        } \
        type & ClassName##::Pop##var() \
        { \
                return m_##var; \
        } \
        void ClassName##::Set##var(type arg) \
        { \
                m_##var = arg; \
        } \
分别在.h和.cpp中使用这两个宏，修改原有的在头文件中定义字段为：在头文件中声明字段，.cpp文件中实现字段的存取值函数
示例：
修改原有在头文件中的
BE_DATA_VALUE(double, SaftyHeight)(double, SaftyHeight)
为头文件文件中
DECLARE_PROPERTY(double, SaftyHeight)，
和cpp文件中
DEFINE_PROPERTY(PDIWT::Waterway::Lock::DolphinColumnP1_P11,double, SaftyHeight)

**Comment by runehacker** [comment]
good idea

**Comment by DawsenSu** [comment]
建议将此两宏定义放入BeDefiner.h,文件中，按需取用
